<?php include "inc/header.php"?>
<?php include "templates/banner.php"?>
<?php include "templates/cursos_destaques.php"?>
<?php include "templates/tipos_de_curso.php"?>
<?php include "templates/depoimentos.php"?>
<?php include "templates/beneficios.php"?>
<?php include "templates/duvidas_frequentes.php"?>
<?php include "templates/modelo.php"?>
<?php include "inc/footer.php"?>